dist: bionic
language: python

install:
  - pip install coveralls tox
script:
  - tox -e $TOX_ENV
after_success:
  - coveralls --verbose

matrix:
  include:
    - python: 3.8
      env: TOX_ENV=py38
  allow_failures:
    - python: pypy3
      env: TOX_ENV=pypy3
