dist: xenial
language: python
sudo: false

install:
  - pip install coveralls tox
script:
  - tox -e $TOX_ENV
  - python setup.py check -r
after_success:
  - coveralls --verbose

matrix:
  include:
    - python: 3.6
      env: TOX_ENV=py36
    - python: 3.7
      env: TOX_ENV=py37
    - python: pypy3
      env: TOX_ENV=pypy3
  allow_failures:
    - python: pypy
      env: TOX_ENV=pypy
