language: python
sudo: false
env:
  - TOX_ENV=py27-pip156
  - TOX_ENV=py27-pip611
  - TOX_ENV=py33-pip156
  - TOX_ENV=py33-pip611
  - TOX_ENV=py34-pip156
  - TOX_ENV=py34-pip611
  - TOX_ENV=pypy-pip156
  - TOX_ENV=pypy-pip611
install:
  - pip install coveralls tox
script:
  - tox -e $TOX_ENV
  - python setup.py check -r
after_success:
  - coveralls --verbose
